version: "2.1"
services:
  lottery_app:
    build: ./simple_app
    links:
      - mongodb
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    restart: on-failure
  mongodb:
    image: mongo:latest
    restart: on-failure
