version: "2.1"
services:
  gilmor_app:
    build: ./gilmor_app
    links:
      - mongodb
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    volumes:
      - ./gilmor_app/python/:/src
    restart: on-failure
  mongodb:
    image: mongo:latest
    restart: on-failure
